### ISSUE TITLE
[Issue]  Docstring checklist for V3

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#320]
### Pertinent to issue #292

- [x] Find the Docstring convention source. 
We were using Numpy convention before, and this was documented [here](https://github.com/magpylib/magpylib/blob/2.3.0-beta/docs/README.md). The newest docstrings are of an unknown format and are being interpreted wrongly by Sphinx 1.8, which uses [Napoleon](https://www.sphinx-doc.org/pt_BR/master/usage/extensions/napoleon.html) for identifying the docstrings and turning them into web content, which limits us to Numpy and Google style docstrings.
- [x] Confirm if we want to write method docstrings on the class docstrings of each class
This can cause issues as there is no source of truth for the methods, as they are manually declared in the class docstring. I haven't checked how Intellisense deals with this.
- [x] Confirm if we want to get rid of example code from the docstrings
Previous docstrings had example code such as the following, which are rendered on the documentation page:
```python
 """
    Create a collection of :mod:`magpylib.source` objects for common manipulation.

    Parameters
    ----------
    sources : source objects
        python magic variable passes source objects to the collection at initialization.

    Attributes
    ----------
    sources : list of source objects
        List of all sources that have been added to the collection.

    Example
    -------
        >>> from magpylib import source, Collection
        >>> pm1 = source.magnet.Box(mag=[0,0,1000],dim=[1,1,1])
        >>> pm2 = source.magnet.Cylinder(mag=[0,0,1000],dim=[1,1])
        >>> pm3 = source.magnet.Sphere(mag=[0,0,1000],dim=1)
        >>> col = Collection(pm1,pm2,pm3)
        >>> B = col.getB([1,0,1])
        >>> print(B)
        [9.93360625e+01 1.76697482e-14 3.12727683e+01]
    """
```
![image](https://user-images.githubusercontent.com/7332704/120717031-4915b100-c49d-11eb-8322-0ca2f7b083f7.png)

Current Docstrings lack this.

- [x] Confirm if we want a thorough documentation page on the `__init__.py` docstring 
Current `__init__.py` contains resource links and other explanations besides the docstrings themselves, check if we want this here or in a more accessible introduction page.

**Comment by lucasgcb** [comment]
- We're going to Numpy Docstring convention, to be resolved soon
- Remove method explanation from Class docstrings, leave them to their own methods
- Examples will return soon (#294)
- Yes, we'll have intelissense previews of the larger doku. Works well on VSCode
