### ISSUE TITLE
User 3D display representation

### ISSUE THREAD

**Issue by Alexboiboi** [magpylib/magpylib#414]
# Context
For the upcoming v4 version we implemented the `style` parameter for all `sources` and `sensors`. The user can attach a custom `mesh` object to an existing representation via `style.mesh3d`.

# Problems:
- `plotly` backend  only
- `mesh3d` object only
- not extendable without breaking the api

# Goal:
We should define a stable and extendable api to allow the user to add or replace an object representation with a single or multiple traces.

# Tasks
- [x] agree on a definitive but extendable api
- [x] implement new concepts
- [x] write tests
- [x] update docs (after merge in docs_v4)

**Comment by Alexboiboi** [comment]
@OrtnerMichael What do you think of this ?

**Comment by Alexboiboi** [comment]
example code

```python
import numpy as np
import magpylib as magpy

cuboid = magpy.magnet.Cuboid(magnetization=(1,0,0), dimension=(3, 3 ,3), position=(10,0,0)).rotate_from_angax([72] * 5, "z", anchor=(0, 0, 0), start=0, increment=True)
cuboid.style.model3d.show = False
cuboid.style.model3d.extra = [
    {
        'backend': 'matplotlib',
        'trace': {
            'type':'plot',
            'xs': np.array([-1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, 1,  1, -1])/2, 
            'ys': np.array([-1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1])/2, 
            'zs': np.array([-1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1])/2,
            'ls': '-',
        },
        'show': True
    },
    {
        'backend': 'plotly',
        'trace': {
            'type': 'scatter3d',
            'x': np.array([-1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, 1,  1, -1])/2, 
            'y': np.array([-1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1])/2, 
            'z': np.array([-1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1])/2,
            'mode':'lines',
        },
        'show': True,
    },
    {
        'backend': 'plotly',
        'trace': {
            'type': 'mesh3d',
            'i': np.array([7, 0, 0, 0, 4, 4, 2, 6, 4, 0, 3, 7]),
            'j': np.array([0, 7, 1, 2, 6, 7, 1, 2, 5, 5, 2, 2]),
            'k': np.array([3, 4, 2, 3, 5, 6, 5, 5, 0, 1, 7, 6]),
            'x': np.array([-1, -1,  1,  1, -1, -1,  1,  1])/2,
            'y': np.array([-1,  1,  1, -1, -1,  1,  1, -1])/2,
            'z': np.array([-1, -1, -1, -1,  1,  1,  1,  1])/2,
        },
        'show': True,
    },
]

cuboid.display(path=1, backend='plotly')

cuboid.display(path=1, backend='matplotlib')
```

**Comment by Alexboiboi** [comment]
I was still thinking of adding two properties for an extra trace:

```python
- alloworient # default=True (if False prevent the library to orient the object)
- allowdisplace # default=True (if False prevent the library to displace the object)
```

@OrtnerMichael What do you think?

**Comment by laikh** [comment]
under which circumstances would you want this ?
if you dont want to move the 3dmodel attach it to a static object.



Alexandre Boisselet ***@***.***> schrieb am Mo., 29. Nov.
2021, 09:40:

**Comment by Alexboiboi** [comment]
closed by #416

**Comment by Alexboiboi** [comment]
closed by #416
